[[test]]
name = "rd-straight"
cmd = "bril2json < Assignment_2/tests/rd_straight.bril | python3 Assignment_2/Reaching_Definitions.py"

[[test]]
name = "rd-branch"
cmd = "bril2json < Assignment_2/tests/rd_branch.bril | python3 Assignment_2/Reaching_Definitions.py"

[[test]]
name = "rd-loop"
cmd = "bril2json < Assignment_2/tests/rd_loop.bril | python3 Assignment_2/Reaching_Definitions.py"
