cat > turnt.toml << 'EOF'
cmd = "bril2json < {file} | python3 Assignment_2/Reaching_Definitions.py"

[[case]]
file = "Assignment_2/tests/rd_straight.bril"

[[case]]
file = "Assignment_2/tests/rd_branch.bril"

[[case]] 
file = "Assignment_2/tests/rd_loop.bril"
EOF
